### ISSUE TITLE
Unit tests for product repository.

### ISSUE THREAD

**Issue by Arnab-Developer** [berkayyerdelen/Dapper.WebApi#5]
If we can write some unit tests for product repository then it will be a lot better. I want to work on that and send you a PR.

**Comment by Arnab-Developer** [comment]
I have send a PR #6 for this.

**Comment by berkayyerdelen** [comment]
Hi Arnab,
I guess it's breaking the chain rule here because we 're already abstracted the connection by via abstract class. This is the main reason why I didn't want to imp repository or helper since they're looking anti-pattern to me. Also, there's a lot of  way to testing

**Comment by Arnab-Developer** [comment]
Thanks for your review comments.

The main reason why I have created the ```DapperHelper``` class is to separate the actual Dapper dependency from the repository. I can't mock the Dapper methods (```QueryAsync``` for example) in the unit tests because they are extension methods and extension methods are static. Another advantage of separation of Dapper dependency is, if we want to change the database accessing technology from Dapper to some other one (like EF Core for example) in future then our repository will be unchanged.

**Comment by berkayyerdelen** [comment]
I didn't think that abstract the repository layer but still this is a simple implementation of dapper. On the other hand, some people might find it useful so that I merged into master.
Thanks for contribution
Berkay

**Comment by Arnab-Developer** [comment]
Thanks.
